version: '3.9'
services:
  postgres:
    image: postgres:15
    ports:
      - ${POSTGRES_PORT}:5432
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - url-shortener

  redis:
    image: redis
    ports:
      - ${REDIS_PORT}:6379
    volumes:
      - redisdata:/data
    networks:
      - url-shortener

networks:
  url-shortener:

volumes:
  redisdata:
  pgdata:
